services:
  - type: web
    name: miniflux
    env: docker
    repo: https://github.com/askedrelic/miniflux-render.git
    region: oregon
    branch: main
    numInstances: 1
    # https://miniflux.app/docs/configuration.html
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: miniflux-db
          property: connectionString
      - key: RUN_MIGRATIONS
        value: 1
      - key: CREATE_ADMIN
        value: 1
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
      - key: LOG_DATE_TIME
        value: 1
      - key: LISTEN_ADDR
        value: 0.0.0.0:8080
        generateValue: true

databases:
  - name: miniflux-db
    databaseName: miniflux
    user: miniflux
    ipAllowList: []
