services:
  - type: web
    name: miniflux
    plan: free
    env: docker
    repo: https://github.com/askedrelic/miniflux-render.git
    region: oregon
    branch: main
    numInstances: 1
    # https://miniflux.app/docs/configuration.html
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: miniflux-db-free
          property: connectionString
      - key: RUN_MIGRATIONS
        value: 1
      - key: CREATE_ADMIN
        value: 1
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: LISTEN_ADDR
        value: 0.0.0.0:10000

databases:
  - name: miniflux-db-free
    databaseName: miniflux
    plan: free
    user: miniflux
    ipAllowList: []
